/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DefaultHeader: typeof import('./src/components/navigation/DefaultHeader.vue')['default']
    DefaultLayout: typeof import('./src/components/layouts/DefaultLayout.vue')['default']
    DefaultSidebar: typeof import('./src/components/navigation/DefaultSidebar.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb']
    ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: (typeof import('element-plus/es'))['ElDescriptions']
    ElDescriptionsItem: (typeof import('element-plus/es'))['ElDescriptionsItem']
    ElDialog: (typeof import('element-plus/es'))['ElDialog']
    ElDropdown: (typeof import('element-plus/es'))['ElDropdown']
    ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem']
    ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: (typeof import('element-plus/es'))['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: (typeof import('element-plus/es'))['ElMenuItemGroup']
    ElPageHeader: (typeof import('element-plus/es'))['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: (typeof import('element-plus/es'))['ElTag']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MainLayout: (typeof import('./src/components/layouts/DefaultLayout.vue'))['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
